### ISSUE TITLE
Guild config

### ISSUE THREAD

**Issue by Kyle-Stadelmann** [Kyle-Stadelmann/DiscordBot#52]
Certain commands/events presumes the guild in question has a `bot-stuff` and/or `afk-channel` set. Currently, this is just hardcoded to our designated channels. Instead, we need a way to allow guild administrators to set these channels, and a way to persist this information (probably via a guild-config db table) for each guild. 

## Subtasks

- [ ] Create guild-config table (we might expand this with new config ideas in the future, so keep this in mind)
- [ ] Create command for administrators to edit and view this config
- [ ] Update existing hardcoded bot-stuff, afk-channel, etc. in code
