### ISSUE TITLE
Rework afk pic image links

### ISSUE THREAD

**Issue by Kyle-Stadelmann** [Kyle-Stadelmann/DiscordBot#54]
Discord is making some [changes](https://www.techradar.com/pro/security/discord-is-switching-to-temporary-links-to-stop-malware) to their cdn. They're going to be refreshing image links every 24 hours, meaning afk pic images stored on the discord cdn will have their url constantly changing. This disrupts our current afk pic system that uses/stores static cdn links. 

We have two options:
- Migrate to another image host 
- Send each image to a single private channel and instead of storing the url, we store the message id. We use the message id to grab the current image url.

## Subtasks
- [ ] Create afk-pic-backup script to backup files
- [ ] Migrate to new afk pic storage system
- [ ] Create timer to periodically backup afk pic collection

**Comment by Kyle-Stadelmann** [comment]
The saved links no longer work in browser, but when sent in discord, it seems Discord automatically updates the link to make it work properly. So we somehow dodged any bugs with this change to their cdn!
